theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: lilianaoust.fr
  breadcrumb:
    position: none
  summary:
    position: hero
  search:
    active: false
  blocks:
    gallery:
      splide:
        autoplay: false
        arrows: true
        pagination: false
        autoWidth: true
        rewind: false
        speed: 0
        breakpoints:
          '992':
            speed: 300
            destroy: true
  image_sizes:
    design_system:
      lightbox:
        disabled: true