theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: lilianaoust.fr
  breadcrumb:
    position: none
  summary:
    position: hero
  search:
    active: false  